version: "3.9"

services:
  nb_api:
    image: naybinho/nb_api:v1.0.5
    container_name: nb_api-server
    restart: unless-stopped
    network_mode: host
    environment:
      DB_HOST: 192.168.50.2
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: hghgDFGe455677YuytYy
      DB_NAME: nb_api
      DB_SSLMODE: disable
      REDIS_HOST: 192.168.50.2:6379
      REDIS_PASSWORD: hghgDFGe455677YuytYy
      REDIS_DB: "0"
      AUTH_USERNAME: admin
      AUTH_PASSWORD: admin123
      SWAGGER_URL: "http://192.168.1.100:8080"
